### ISSUE TITLE
Can't select anyting

### ISSUE THREAD

**Issue by KoghaandSooga** [tesla15/teslavm#5]
On starting a new machine after typing guest name and setting memory size you cannot select any of the options for hardware or graphics thus it gives errors when you start it.  If you try to select it won't actually click on it.

Expected Behavior: The options should remain when you click on them.

**Comment by tesla15** [comment]
yea, the project is abandoned, currently, our priority is TeslaRC project.

if you feel like, you can fix the code and pull request, im going to merge it
